---
title: "Études"
toc: true
toc-depth: 5
toc-title: "Formations"
toc-location: left
lightbox:
  match: auto
  effect: fade
  desc-position: right
  loop: true
---

# Classes préparatoires aux grandes écoles (2007–2010)

## MPSI au lycée Fabert à Metz

### Devoirs maisons

  * [DM1](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM1.pdf) : Trigonométrie et complexes.
  * [DM2](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM2.pdf) : Trigonométrie et géométrie complexe | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH2.pdf) 
  * [DM3](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM3.pdf) : Théorème de Morley | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH3.pdf)
  * [DM4](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM4.pdf) : Équations différentielles | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH4.pdf)
  * [DM5](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM5.pdf) : Géométrie affine et théorème de Descartes | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH5.pdf)
  * [DM6](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM6.pdf) : Algorithmique et coniques | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH6.pdf)
  * [DM7](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM7.pdf) : Sous-groupes additifs des réels | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH7.pdf)
  * [DM8](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM8.pdf) : Équation fonctionnelle et suite récurrente | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH8.pdf)
  * [DM9](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM9.pdf) : Taylor-Lagrange, convexité et suite implicite | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH9.pdf)
  * [DM10](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM10.pdf) : DL et étude des fonctions monotones | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH10.pdf)
  * [DM11](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM11.pdf) : Théorème de Role, de Bernstein et partitions | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH11.pdf)
  * [DM12](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM12.pdf) : Dénombrement et inégalité de Höldner | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH12.pdf)
  * [DM13](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DM13.pdf) : Etude de l'équivalent d'une suite | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH13.pdf)
  * [DM14](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH14.pdf) : Structures algébriques et automorphismes linéaire | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH14.pdf)
  * [DM15](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH15.pdf) : Arithmétique et sous-groupes distingués | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH15.pdf)
  * [DM16](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH16.pdf) : Matrice et inverse dans un groupe | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH16.pdf)
  * [DM17](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH17.pdf) : Codage RSA et quaternions | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH17.pdf)
  * [DM18](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH18.pdf) : Matrices, déterminant, polynômes | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH18.pdf)
  * [DM19](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH19.pdf) : Polynômes, DES et interpolation | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMsup/DH19.pdf)
  
## MP* au lycée Fabert à Metz

### Devoir maisons

  * [DM1](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM1.pdf) : Étude de l'opérateur aux différences finies | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH1.pdf)
  * [DM2](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM2.pdf) : Nombres algébriques et transcendants | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH2.pdf)
  * [DM3](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM3.pdf) : Étude de bases stables dans une algèbre | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH3.pdf)
  * [DM4](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM4.pdf) : Étude des matrices sans valeur propre réelle | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH4.pdf)
  * [DM5](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM5.pdf) : Nombres p-adiques et remontée modulaire | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH5.pdf)
  * [DM6](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM6.pdf) : Étude autour des suites de Fibonacci | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH6.pdf)
  * [DM7](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM7.pdf) : Étude d'un certain type de suites récurrentes | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH7.pdf)
  * [DM8](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM8.pdf) : Convergence de séries de caractères | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH8.pdf)
  * [DM9](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM9.pdf): Théorème de Weierstrass et Bernstein | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH9.pdf)
  * [DM10](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM10.pdf) : Courbes elliptiques et théorème de Mordell | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH10.pdf)
  * [DM11](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM11.pdf) : Étude des hyperplans de l'espace L(E) | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH11.pdf)
  * [DM12](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM12.pdf) : Rayon spectral et disques de Gershgorin | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH12.pdf)
  * [DM13](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DM13.pdf) : Problèmes de minimisation en dimension n | [Solutions](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/DH13.pdf)
  
### Les colles

  * [Colle 1](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Colle_1.pdf) : Convergence de la fonction zêta de Riemann. 
  * [Colle 2](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Colle_2.pdf) : Théorème de Wirtinger et inégalité isopérimétrique. 
  * [Colle 3](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Colle_3.pdf) : Supplémentarité et forme bilinéaire symétrique. 
  * [Colle 4](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Colle_4.pdf) : Déterminants blocs de matrices orthogonales. 
  * [Colle 5](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Colle_5.pdf) : Espace euclidien et endomorphisme inversible.
  * [Colle 6](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Colle_6.pdf) : Topologie sur le groupe spécial orthogonal. 
  * [Colle 7](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Colle_7.pdf) : Minimum sur le groupe spécial linéaire.
  * [Colle 8](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Colle_8.pdf) : Planche des mines de l'officiel de la taupe.
  * [Colle 9](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Colle_9.pdf) : Planche d'ENS issue de la revue de maths spé. 
  
### Fiches de révisions

 *  [Fiche 0](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_0.pdf) : Rappels de trigonométrie.
  * [Fiche 1](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_1.pdf)  : Structures algébriques. 
  * [Fiche 2](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_2.pdf)  : Espaces vectoriels. 
  * [Fiche 3](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_3.pdf)  : Calcul matriciel.
  * [Fiche 4](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_4.pdf)  : Réduction d'endomorphismes. 
  * [Fiche 5](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_5.pdf)  : Suites numériques. 
  * [Fiche 6](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_6.pdf)  : Séries numériques.
  * [Fiche 7](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_7.pdf)  : Séries entières.
  * [Fiche 8](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_8.pdf)  : Généralisation de la notion d'intégrale.
  * [Fiche 9](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_9.pdf)  : Suites et séries de fonctions.
  * [Fiche 10](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_10.pdf)  : Séries trigonométriques. 
  * [Fiche 11](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_11.pdf)  : Formes bilinéaires et quadratiques.
  * [Fiche 12](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_12.pdf)  : Espaces préhilbertiens complexes.
  * [Fiche 13](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_13.pdf)  : Espaces métriques. 
  * [Fiche 14](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_14.pdf)  : Espaces vectoriels normés. 
  * [Fiche 15](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_15.pdf)  : Fonctions vectorielles.
  * [Fiche 16](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_16.pdf)  : Fonctions de plusieurs variables.
  * [Fiche 17](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_17.pdf)  : Équations différentielles.
  * [Fiche 18](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiche_18.pdf)  : Intégrales doubles. 

Télécharger toutes les fiches au format [PDF](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiches_MP.pdf)  ou toute [l'archive](https://kevinpolisano.github.io/pdf-storage/Prepa/DMspe/Fiches_MP.tar.gz).

### TIPE

Le [travail d'initiative personnelle encadré](https://fr.wikipedia.org/wiki/Travail_d%27initiative_personnelle_encadr%C3%A9) (TIPE) est une épreuve commune à la plupart des concours d'entrée aux Grandes écoles scientifiques.

#### Année 2008-2009

Le thème des TIPE était _L'information_ et mon sujet portait sur les **codes correcteurs**.

[Télécharger mon TIPE sur les codes correcteurs BCH](https://kevinpolisano.github.io/pdf-storage/Prepa/TIPE/TIPE_Codes_Correcteurs.pdf)

#### Année 2009-2010

Le thème des TIPE était _Surfaces_ et mon sujet portait sur les **cercles de Villarceau**.

[Télécharger mon TIPE sur les cercles de Villarceau](https://kevinpolisano.github.io/pdf-storage/Prepa/TIPE/TIPE_Villarceau.pdf)

J'ai présenté ce TIPE aux Concours Commun Polytechnique, à titre d'exemple je mets à disposition les documents suivants :

  * [La fiche synoptique](https://kevinpolisano.github.io/pdf-storage/Prepa/TIPE/Fiche_Synoptique_Villarceau.pdf)
  * [Le support de présentation](https://kevinpolisano.github.io/pdf-storage/Prepa/TIPE/TIPE_Villarceau_Presentation.pdf) 
  * [La soutenance orale](https://kevinpolisano.github.io/pdf-storage/Prepa/TIPE/TIPE_Villarceau_Soutenance.pdf)  

# École d'ingénieur Ensimag (2010–2013)

## Ensimag 1A

La première année à l'Ensimag était une année de tronc commun avec quelques matières à la carte. Ci-dessous la liste des cours, TP et projets réalisés au cours de l'année pour une vitrine de ce qui se faisait à l'Ensimag.

### Liste des cours suivis

#### Mathématiques appliquées

  * Analyse pour l'ingénieur
  * Méthodes numériques de base
  * Probabilités appliquées
  * Recherche opérationnelle
  * Théorie des langages

#### Logiciel et matériel de base pour l'informatique

  * Architecture des ordinateurs
  * Algorithmique et structure de données
  * Logiciel de base, programmation bas niveau
  * Projet logiciel en C
  * Réseaux et télécommunication

#### Options scientifiques

  * Analyse avancée
  * Probabilités avancées
  * Interface graphique utilisateur

#### Sciences humaines, économiques, du management et entreprise (SCHEME)

  * Économie générale
  * Gestion d'entreprise et communication
  * Projet professionnel personnel
  * Anglais
  * Italien
  * Activités sportives

### Projets réalisés

#### Projet C

Réalisation en C d'un encodeur/décodeur JPEG | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Projets/Projet-C.pdf)

#### Interface utilisateur graphique 1

Implémentation en ADA/SDL d'une boite à outils graphiques type _"Paint"_, programmation des primitives bas niveau puis d'une toolglass comme intéracteur | [Sujet](http://brouet.imag.fr/fberard/IUG/ProjetToolkit) 

#### Interface utilisateur graphique 2

Implémentation dans le langage Tcl/Tk d'un navigateur de fichier.

#### Méthodes numériques

Modélisation d'un écoulement de peinture par une équation différentielle et résolution numérique effectuée par différences finies et algorithmes itératifs en Scilab | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Projets/Methodes_Numeriques.pdf)

#### Shell Unix

Réalisation d'un script bash permettant de générer à partir d'images une galerie HTML. 

#### Analyse pour l'ingénieur

Calcul de transformées de Fourier sur Scilab | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Projets/Analyse.pdf)

### Travaux pratiques

#### Algorithmique

  * [TPL1](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Algorithmique/Algo1_TPL1.pdf) : Simulation du Taquin "Embouteillage".
  * [TPL2](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Algorithmique/Algo1_TPL2.pdf) : Recherche d'une solution optimale au Taquin. 
  * [TPL3](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Algorithmique/Algo2_TPL1.pdf) : Programmation générique des arbres binaires de recherche AVL et applications. 
  * [TPL4](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Algorithmique/Algo2_TPL2.pdf) : Files de priorités et arbres de Huffmann.

#### Analyse

  * [TD1](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Analyse/Analyse_TD1.pdf) : Exercices sur la théorie de la mesure | [Solutions](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Analyse/Analyse_TD1_corr.pdf)
  * [TD2](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Analyse/Analyse_TD2.pdf) : Exercices sur l'intégrale de Lebesgue | [Solutions](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Analyse/Analyse_TD2_corr.pdf)
  * [TD3](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Analyse/Analyse_TD3.pdf) : Exercices sur les intégrales paramétrées | [Solutions](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Analyse/Analyse_TD3_corr.pdf)
  * [TD4](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Analyse/Analyse_TD4.pdf) : Exercices sur la transformée de Fourier. 
  * [Annexe](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Analyse/Analyse_TD1.pdf) : Exemple d'un ensemble non mesurable.

#### Économie

  * [Cours](https://kevinpolisano.github.io/pdf-storage/Ensimag-1A/Economie/Economie_cours.pdf) : Introduction à l'économie générale.

## Ensimag 2A

En deuxième année j'ai choisi la filière MMIS (Modélisation Mathématique, Images et Simulations) option IRVM (Image, Réalité Virtuelle et Multimédia). Ci-dessous la liste des cours, TP et projets réalisés au cours de l'année.

### Liste des cours suivis

#### Tronc commun MMIS

  * Algorithmique et programmation orientée objet
  * Principes et méthodes statistiques
  * Principes des systèmes de gestion de base de données
  * Systèmes d'exploitation et programmation concurrente
  * Projet base de données
  * Projet génie logiciel
  * Projet de spécialité

#### Spécialité Image, Réalité Virtuelle et Multimédia**_

  * Équations aux dérivées partielles et différences finies
  * Méthodes numériques avancées
  * Modélisation géométrique
  * Multimédia
  * Graphique 3D
  * Image et morphologie mathématique
  * Introduction à la recherche en laboratoire
  * Modèles d'EDP avancés
  * Modélisation et programmation
  * Traitement statistique du signal et des images
  * Traitement d'image

#### Sciences humaines, économiques, du management et des entreprises

  * Pratique de gestion de l'entreprise
  * Management, délégation
  * Gestion de projet
  * Droit des affaires
  * Projet professionnel personnel
  * Anglais
  * Activités physiques et sportives

### Projets réalisés

#### Algorithmique et programmation orientée objet

Implémentation en Java d'un programme permettant la visualisation d'objets 3D et le rebouchage de trous dans un maillage | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/APOO.pdf)

#### Système de gestion de bases de données

Implémentation en Java et SQL d’une base de données pour gérer les réservations dans un groupe de restaurants. | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/BD.pdf)

#### Modélisation géométrique 

Implémentation en Matlab d'une approximation d'un nuage de points par des courbes de Bézier | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Modelisation_geometrique.pdf) 

#### Principes et méthodes statistiques

Analyse des défauts d'une cuve et vérifications expérimentales à base de simulations sur R | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Methodes_statistiques.pdf)

#### Génie logiciel

Réalisation en ADA d'un compilateur objet de type Java | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Genie_Logiciel.tar.gz)

#### Graphique 3D

Implémentation en C++, de l'API OpenGL avec QGLViewer d'une scène animée 3D de ski dans un décor de montagne | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Graphique-3D.pdf)

#### Modélisation et programmation 

Implémentation en C++ d'un programme réalisant un maillage de surface par une triangulation de Delaunay basée sur les complexes simpliciaux | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Modelisation_programmation.pdf)

#### Multimédia

Implémentation en C d'un programme de tatouage d'images, étude de la robustesse lorsque celles-ci sont soumises à des transformations géométriques | [Sujet](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Multimedia.pdf)

#### Introduction à la recherche en laboratoire 

Étude mathématique et simulation numérique sous Matlab de la dynamique neuronale. Recherche au sein de l'équipe BIPOP de l'INRIA d'un nouveau modèle doté d'un seuil de décharge variable, application à la prédiction neuronale | [Rapport](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/IRL_rapport.pdf) | [Slides](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/IRL_slides.pdf) | [Sources](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/IRL_sources.tar.gz)

#### Projet de spécialité

Détection du touché sur une surface multitouch 3D munie d'une caméra infrarouge (Cubtile). Travail réalisé au sein de l'équipe IIHM du LIG. Implémentation en C++ et OpenCV | [Sujet](http://brouet.imag.fr/fberard/ProjetImage/CubtileTouch) | [Slides](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Projet-specialite_slides.pdf) | [Sources](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Projet-specialite_sources.tar.gz)

#### Stage 2A 

Reconstruction analytique de régions d'intérêts en imagerie médicale. Travail réalisé au sein de l'équipe GMCAO du laboratoire TIMC. Implémentation sous Matlab d'un algorithme visant à réduire l'exposition des patients aux rayons X |  [Article](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Stage-2A_sujet.pdf) |  [Rapport](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Stage-2A_rapport.pdf) |  [Slides](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Stage-2A_slides.pdf) |  [Appendix](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Stage-2A_appendix.pdf) |  [Sources](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Projets/Stage-2A_sources.tar.gz) 

### Travaux pratiques

#### Méthodes numériques avancées

  * [TP1](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Methodes_numeriques/MNA_TP1.pdf) : Résolution d'équations différentielles ordinaires en C par les méthodes explicites de Runge-Kutta et Adams, et application à un modèle de propagation d’une épidémie dans une population. 
  * [TP2](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Methodes_numeriques/MNA_TP2.pdf) : Implémentation en C de différentes méthodes de calcul numériques d’intégration, dont une à pas adaptatif.
  * [TP3](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Methodes_numeriques/MNA_TP3.pdf) : Implémentation en C de méthodes de résolution de systèmes linéaires efficaces afin de résoudre et d'animer l’équation de la chaleur : méthodes de Krylov, stockage creux et schéma implicite utilisés. 

#### Modélisation et programmation

  * [TP1](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Modelisation_programmation/MP_TP1.pdf) : Implémentation en C++ d'une classe Dvector. 
  * [TP2](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Modelisation_programmation/MP_TP2.pdf) : Améliorations apportées par surcharge d'opérateurs. 
  * [TP3](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Modelisation_programmation/MP_TP3.pdf) : Extension aux classes Dmatrix pour l'algèbre linéaire. 
  * [TP4](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Modelisation_programmation/MP_TP4.pdf) : Manipulation des patrons et de la STL sur les maillages. 

#### Traitement d'image

  * [TP1](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Traitement_images/TI_TP1.pdf) : Travail sur l'histogramme d'une image en niveaux de gris, amélioration de contraste, histogramme cumulé, filtrage rétinien.
  * [TP2](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Traitement_images/TI_TP2.pdf) : Implémentation en C de filtrages linéaires (gaussiens, fft, etc) et non linéaires (médians, adaptatifs, bilatéraux). 
  * [TP3](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/Traitement_images/TI_TP3.pdf) : Implémentation en C d'algorithmes de détection de contours : par gradient (Canny, seuillage par hystérésis) et par Laplacien.

#### Système d'exploitation et programmation concurrente 

  * [TP1](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/SEPC/SEPC_TP1.pdf) : Implémentation en C d'un allocateur de mémoire. 
  * [TP2](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/SEPC/SEPC_TP2.pdf) : Implémentation en C d'un shell. 
  * [TP3](https://kevinpolisano.github.io/pdf-storage/Ensimag-2A/SEPC/SEPC_TP3.pdf) : Synchronisation entre _threads_ (processus légers) à l'aide de moniteurs POSIX et de sémaphores. 
  
## Master 2 de recherche MSIAM

J'ai effectué ma troisième année en M2 MSIAM qui propose des cours communs avec l'Ensimag.

### Articles de recherches étudiés  

#### Imagerie médicale

Solving the interior problem of computed tomography using a priori knowledge. M. Courdurier et al. (2008) | [Article](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Imagerie_medicale/IM_article.pdf) | [Rapport](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Imagerie_medicale/IM_rapport.pdf) | [Slides](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Imagerie_medicale/IM_slides.pdf) 

#### Calcul exact

Quadratic-Time Certificates in Linear Algebra. Erich L. Kaltofen et al. (2009) | [Article](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Calcul_exact/CE_article.pdf) | [Rapport](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Calcul_exact/CE_rapport.pdf) | [Slides](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Calcul_exact/CE__slides.pdf) 

#### Modèles géométriques pour l'image

Meaningful scales detection along digital contours for unsupervised local noise estimation. Bertrand Kerautret et Jacques-Olivier Lachaud (2012) | [Article](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Modeles_geometriques/MG_article.pdf) | [Rapport](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Modeles_geometriques/MG_rapport2.pdf) 

#### Modélisation surfacique

Transfinite surface interpolation over irregular n-sided domains. Tamás Várady (2011) | [Article](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Modelisation_surfacique/MS_article.pdf) | [Slides](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Modelisation_surfacique/MS_slides.pdf)

#### Reconstruction géométrique

Object Removal by Exemplar-Based Inpainting. A. Criminisi (2003) | [Article](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Reconstruction_geometrique/RG_article.pdf) | [Slides](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Reconstruction_geometrique/RG_slides.pdf)

#### Ondelettes

Une introduction aux ondelettes monogéniques à partir d'un article de M. Unser (2009) | [Article](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Ondelettes/Ondelettes_article.pdf) | [Slides](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Ondelettes/Ondelettes_slides.pdf)

### Projets réalisés  

#### Méthodes inverses

Assimilation de données en Matlab sur l'attracteur de Lorenz utilisé comme modèle météorologique | [Sujet](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Methodes_inverses/MI_sujet.pdf) | [Rapport](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Methodes_inverses/MI_rapport.pdf) | [Sources](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Methodes_inverses/MI_sources.tar.gz)

#### Vision par ordinateur

Implémentation en C++ d'un algorithme du Mean Shift amélioré pour la segmentation d'images | [Article](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Vision_par_ordinateur/VPO_article.pdf) | [Rapport](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Vision_par_ordinateur/VPO_rapport.pdf) | [Sources](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Vision_par_ordinateur/VPO_sources.tar.gz)

#### Modèles géométriques et morphologiques pour l'image  

Implémentation en C++ d'algorithmes classiques en traitement d'image | [Sujet](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Modeles_geometriques/MG_sujet.pdf) | [Rapport](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Modeles_geometriques/MG_rapport.pdf) | [Sources](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Modeles_geometriques/MG_sources.tar.gz)

#### Visualisation scientifique

Implémentation en Processing (surcouche de Java) d'un programme d'importation de données météorologiques (température, pression, pollution, etc) et exportation sur Google Earth des cartes | [Rapport](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Visualisation_scientifique/VS_rapport.pdf) | [Sources](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Visualisation_scientifique/VS_sources.tar.gz)

#### Reconstruction géométrique

Implémentation en C++ avec la libQGLViewer d'un programme de reconstruction de surfaces | [Sujet](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Reconstruction_geometrique/RG_sujet.pdf) | [Rapport](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Reconstruction_geometrique/RG_rapport.pdf) | [Sources](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/Reconstruction_geometrique/RG_sources.tar.gz)

#### Projet de fin d'études   

Du mois de février au mois de juillet, j'ai travaillé au Laboratoire Jean Kuntzmann sur la _"Détection d'anisotropie dans les images via la transformée en ondelettes monogéniques"_ | [Sujet](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/PFE/PFE_sujet.pdf) | [Rapport](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/PFE/PFE_rapport.pdf) | [Slides](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/PFE/PFE_slides.pdf) | [Sources](https://kevinpolisano.github.io/pdf-storage/M2-MSIAM/PFE/PFE_matlab.tar.gz)

## Ambassadeur de promo

Désigné ambassadeur de promotion dans le cadre de la remise des diplômes de l'INP et de l'Ensimag le samedi 29 novembre 2014, j'ai eu l'opportunité de pouvoir représenter ma promotion et faire un [discours](https://kevinpolisano.github.io/pdf-storage/Doctorat/discours_remise_des_diplomes.pdf) sur mon parcours et mes activités de recherches.

<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; text-align: center;">
  <iframe src="https://www.youtube.com/embed/YkGMbwH2qeM?si=REcDmhJSEZHVzGNl"
          title="YouTube video player"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen
          referrerpolicy="strict-origin-when-cross-origin"
          style="position: absolute; top: 0; left: 50%; transform: translateX(-50%); width: 100%; height: 100%;">
  </iframe>
</div>


<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; text-align: center;">
  <iframe src="https://www.youtube.com/embed/Bu2bvjsEatM?si=3z3VsfTbhqr8Q5xu"
          title="YouTube video player"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen
          referrerpolicy="strict-origin-when-cross-origin"
          style="position: absolute; top: 0; left: 50%; transform: translateX(-50%); width: 100%; height: 100%;">
  </iframe>
</div>


# Doctorat (2013–2017)

## Sujet de thèse

J'ai effectué ma thèse au laboratoire Jean Kuntzmann, financée par une bourse du CNRS, sous la direction de **Valérie Perrier**, **Marianne Clausel** et **Laurent Condat**.

- [Sujet de thèse](https://kevinpolisano.github.io/pdf-storage/Doctorat/Sujet-these.pdf) : Modélisation de textures anisotropes par la transformée en ondelettes monogéniques 

## Activités transversales

- [École d'été ESSIM 2013](https://scala.uc3m.es/essim2013/welcome.html) à Madrid.
  - Projet réalisé : [Modelling the trajectory of a skydiver](https://kevinpolisano.github.io/pdf-storage/Doctorat/ESSIM_report.pdf)
  
- Cours particuliers de L2 : un semestre de cours d’analyse dispensé à un étudiant polyhandicapé.
  
- Formation [From Chaos to Complexity](https://videos.univ-grenoble-alpes.fr/search/?q=chaos+and+complexity) (janvier 2014)

- Organisation de la journée des doctorants (25 avril 2014)

- Organisation d'un groupe de travail : Préparation à la visite d'**Emmanuel Candès** et remise du prix Jean Kuntzmann. Étude des articles "phares" de l'auteur et présentation d'exposés (tous les jeudi jusqu'au 16 juin 2014)
  - Ma présentation : [Introduction to Compressive Sampling](https://kevinpolisano.github.io/pdf-storage/Doctorat/intro-compressive-sampling.pdf)
  - Notre [interview](https://kevinpolisano.github.io/pdf-storage/Doctorat/candes-interview.pdf) d'**Emmanuel Candès**
  
- Fête de la science 2015 : organisation d'un stand grand public sur le thème *Comprendre les circulations atmosphériques et océanographiques*, à Minatec.

- École d'été *Big Optim* (juin 2015) : optimisation convexe à grande échelle, algorithmes proximaux et applications, à Gipsa-Lab.

- Tables rondes Forum « Imagine ton avenir » (FITA, janvier 2016) pour témoigner sur la recherche.

- Interviews MAP (février 2016) : entretien avec des étudiants pour leur « Module d’accompagnement professionnel ».

- Math en Jeans (avril 2016) : Exposé devant des élèves des collèges Malraux (Voreppe) et Barnave (St Egrève)

- Visite des étudiants du Cycle Préparatoire Polytechnique (CPP, avril 2017) et présentation de l’école et des projets numériques au cours du cursus de l'Ensimag.

- Encadrement d'un projet filé 2A Ensimag (janvier à mai 2017) : [Comparaison de méthodes paramétriques pour la détection spectrale](https://kevinpolisano.github.io/pdf-storage/Doctoratrapport_polisano_bouton_buthod-garcon_vincent.pdf)

- Organisation d’un groupe de lecture « Analyse de graphes par ondelettes », avec Nicolas Tremblay (Gipsa), Sophie Achard (LJK) et Aurélien Gourrier (Liphy).
  
## Soutenance thèse

Le 12 décembre 2017, j'ai soutenu ma [thèse de doctorat](https://polisano.pages.math.cnrs.fr/uploads/polisano-modelisation-2017.pdf), en donnant cette [présentation](https://polisano.pages.math.cnrs.fr/uploads/polisano-modelisation-2017-slides.pdf) devant le jury composé de :

- **Valérie Perrier**, Professeur, Grenoble INP, Directrice de thèse.
- **Gabriel Peyré**, Directeur de recherche, CNRS Délégation Paris, Rapporteur.
- **Frédéric Richard**, Professeur, Université Aix-Marseille, Rapporteur.
- **Marianne Clausel**, Professeur, Université de Lorraine, Co-encadrante.
- **Laurent Condat**, Chargé de recherche, CNRS Délégation Alpes, Co-encadrant.
- **Pierre-Armand Weiss**, Chargé de recherche, CNRS Délégation Midi-Pyrénées, Examinateur.
- **Anne Estrade**, Professeur, Université Paris 5, Examinateur.
- **Annick Montanvert**, Professeur, Université Grenoble Alpes, Présidente.

<div style="position: relative; padding-bottom: 56.25%; height: 0; overflow: hidden; max-width: 100%; text-align: center;">
  <iframe src="https://www.youtube.com/embed/LhPJNF3PO6U?si=RgV4A0_8OwWadUJZ"
          title="YouTube video player"
          frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
          allowfullscreen
          referrerpolicy="strict-origin-when-cross-origin"
          style="position: absolute; top: 0; left: 50%; transform: translateX(-50%); width: 100%; height: 100%;">
  </iframe>
</div>
  
> Soutenance filmée dans l'auditorium du bâtiment IMAG
  
Pour plus de détails sur les activités menées, voir mon [CV académique](https://polisano.pages.math.cnrs.fr/uploads/cv.pdf).
